# Lesli
# 
# Copyright (c) 2025, Lesli Technologies, S. A.
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program. If not, see http://www.gnu.org/licenses/.
# 
# Lesli · Ruby on Rails SaaS Development Framework.
# 
# Made with ♥ by LesliTech
# Building a better future, one line of code at a time.
# 
# @contact  hello@lesli.tech
# @website  https://www.lesli.tech
# @license  GPLv3 http://www.gnu.org/licenses/gpl-3.0.en.html
# 
# // · ~·~     ~·~     ~·~     ~·~     ~·~     ~·~     ~·~     ~·~     ~·~
# // · 



# -·-   -·-   -·-   -·-   -·-   -·-   -·-   -·-   -·-   -·-   -·-   -·-   -·-
# REUSABLE GITHUB ACTIONS WORKFLOWS DESIGNED TO BE USED ACROSS 
# THE LESLI FRAMEWORK REPOSITORIES
# -·-   -·-   -·-   -·-   -·-   -·-   -·-   -·-   -·-   -·-   -·-   -·-   -·-



# Specs for The Lesli Framework
# -·-   -·-   -·-   -·-   -·-   -·-   -·-   -·-   -·-   -·-   -·-   -·-   -·-
name: "Lesli tests workflow"
on:
  push:
    branches: [master]  # Execute when push only for the master branch
  workflow_dispatch:    # This allows the action to be executed on demand
  workflow_call:        # This makes it reusable across all the lesli repos
  pull_request:         # Execute this workflow automatic on any new PR

jobs:
  lesli-test-brakeman:
    name: Run lesli-test-brakeman
    uses: LesliTech/LesliActions/.github/workflows/lesli-test-brakeman.yaml@master
    with:
      branch: ${{ github.ref_name }}
  lesli-test-engine-postgresql:
    name: Run lesli-test-engine-postgresql
    needs: lesli-test-brakeman
    uses: LesliTech/LesliActions/.github/workflows/lesli-test-engine-postgresql.yaml@master
    with:
      branch: ${{ github.ref_name }}

  lesli-test-engine-sqlite:
    name: Run lesli-test-engine-sqlite
    needs: lesli-test-engine-postgresql
    uses: LesliTech/LesliActions/.github/workflows/lesli-test-engine-sqlite.yaml@master
    with:
      branch: ${{ github.ref_name }}
